name: DAST

on:
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: |
          node app.js &
          sleep 5

      - name: OWASP ZAP Baseline Scan
        run: |
          docker run --network host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://127.0.0.1:3000